name = "familytree"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "familytree-db"
database_id = "local"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "familytree-images"
