name = "familytree"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "familytree-db"
database_id = "c81d4a6c-01c2-4655-8cfc-11c829b580c3"
